### ISSUE TITLE
toysat --pb not running for this input?

### ISSUE THREAD

**Issue by anithag** [msakai/toysolver#15]
I am a bit confused with the output of toysat when used with --pb option with a particular instance. With the attached file in opb format, I don't see any results. The solver simply quits. How should I interpret it? [Note that, I am able to run other small testcases]

(oops I am not able to attach the testcase: Error says, I can only attach png/gif/jpg).

$./toysat --pb min.txt
...
c   loop-0.3.0
c   mtl-2.2.1
c   multiset-0.3.0
c   mwc-random-0.13.3.2
c   old-locale-1.0.0.6
c   parse_dimacs-1.3
c   parsec-3.1.9
c   prettyclass-1.0.0.0
c   primes-0.2.1.0
c   process-1.2.0.0
c   pseudo-boolean-0.1.2.0
c   queue-0.1.2
c   sign-0.4.2
c   stm-2.4.2
c   temporary-1.4.2
c   time-1.4.2
c   type-level-numbers-0.1.1.1
c   unbounded-delays-0.1.0.9
c   unordered-containers-0.2.4.0
c   vector-space-0.10.2
c command line = ["--pb","min.txt"]
c use --random-gen="508655808 1659196849 1072282525 3122131391 2423936777 1470284561 213976922 2135472621 656322979 1736236859 836210351 718055101 2439291645 698284455 1728478182 4200647059 780576319 1395652772 1809761089 1161594570 3393332917 1258869760 3303925131 3821121962 839083773 623863976 2922618724 4257593731 612410646 1831897773 3406159972 451678311 3100798560 270778209 3198629679 4013908656 958233189 292876876 2867125610 3819227241 458541713 317087768 1244229644 2295026626 3631368879 3199260981 496888532 3657224610 2695621227 809055206 3290211606 2697954526 2890414411 2404806155 600503903 3675319417 2407495405 350422873 1020310661 3124076876 3983772080 184343369 3473187996 3041176272 3402092637 2164500065 2273527990 1765178842 1167047973 3290728564 2159859327 415970822 1690776772 166261180 226758578 2392621182 4226447651 3783026362 3945561292 1033688798 2541519130 3872405237 1088028221 2145989806 3705750787 2501348722 2549116307 1289291783 1599799544 9362808 1224565366 3787978058 3447889198 2270723997 182538429 2791144496 1573000555 2029625764 1100056224 846765250 57413492 3580064767 1822544135 4096134418 3416820127 2431702436 3448232906 2151415644 803190017 1950330758 1973986151 3665564905 1466797908 2740103655 1553011071 2308927903 1302084616 1908443575 3559058450 2171481495 1819245345 123616344 1255356065 853921188 1081220811 2470076706 3240704868 2929925922 2027959876 3894361981 3230106602 3875057153 3873196943 3115822817 3596939265 4223093735 1093765989 2782501417 2918619252 1529541314 2943944454 3346408920 1751122346 1516570277 411496114 1726015395 133798522 3666797293 989976569 2524907507 1470666714 1004076047 1786675275 944337483 3960873041 3800640395 3234416482 2450253656 3426625219 577645587 1281486344 3237028168 49601347 2759874733 410018306 962625752 870648904 3019639816 1304511203 702205597 2466784589 2596166309 3105668713 435911710 2788389570 178234977 3521247614 281479117 3073375077 3587377144 3940073798 1292398691 2468063072 1491098614 125006015 1851870200 3304861472 3056320679 1892447432 1699234489 72923534 249208249 1313134150 3284884195 1043155944 145413631 1232452045 3846412899 2596913042 135206283 1920525154 3224256571 2606646866 2363165714 334320061 3118137870 2873535947 2663893723 1767274489 3805110432 197165836 2299009718 1229451936 124580119 686719293 1433257991 1026991935 3947179893 3287938108 3052292695 421871518 3890023557 13061487 2251739276 3997058609 3005574923 2721340470 548864857 3382230145 4268383098 895357657 938342390 1607099006 3209781642 1269171289 437798892 781217359 12647583 4284326039 3856519783 2624495589 1762546839 2987342026 21299414 3305424948 3220792733 2410508663 2138444733 3403377563 499398959 377265549 7301068 2535872731 815182677 911894205 162302098 255 362436" option to reproduce the execution
endOfInput

**Comment by msakai** [comment]
Thank you for reporting the problem.
I released the new version pseudo-boolean-0.1.3.0 with relaxed grammar that allows omitting spaces at the end of weighted terms.

c.f. https://github.com/msakai/pseudo-boolean/issues/2
