### ISSUE TITLE
build script should not ask for sudo password and install system wide deps

### ISSUE THREAD

**Issue by anterak13** [msakai/toysolver#20]
Hi, I find the build scripts "aggressive", asking for sudo passwords, modifying apt lists and performing system wide installs of deps without any warning or warning info. Perhaps you could modify the readme to list the ghc dep and change the script so that it does not function in sudo mode by default and just fails if deps are missing ?

**Comment by msakai** [comment]
Sorry for not responding long time.
Those scripts are scripts that I used for building binary package on a fresh virtual machine, and not intended to be used by normal user.
I moved those scripts into `misc/`.

Thank you for your comment.
