### ISSUE TITLE
Fail to install, particularly toysolver-0.6.0

### ISSUE THREAD

**Issue by kwyip** [msakai/toysolver#23]
I get everything installed until toysolver-0.6.0.
The error is 
```
cabal: Entering directory '.'
Configuring toysolver-0.6.0...
Preprocessing library for toysolver-0.6.0..
Building library for toysolver-0.6.0..
Preprocessing executable 'toyconvert' for toysolver-0.6.0..
Building executable 'toyconvert' for toysolver-0.6.0..
Preprocessing executable 'toyqbf' for toysolver-0.6.0..
Building executable 'toyqbf' for toysolver-0.6.0..
Preprocessing executable 'toysat' for toysolver-0.6.0..
Building executable 'toysat' for toysolver-0.6.0..
Preprocessing executable 'toysmt' for toysolver-0.6.0..
cabal.real: can't find source for Smtlib/Parsers/CommonParsers in app/toysmt,
Smtlib, dist/build/toysmt/autogen, dist/build/global-autogen
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
toysolver-0.6.0-JkBmbHh9l5D16lXt1wYJQ2 failed during the building phase. The
exception was:
ExitFailure 1
```

The line "cabal.real: can't find source for Smtlib/Parsers/CommonParsers in app/toysmt" is causing the problem. How to deal with this? I am using Mac OS maverick.

**Comment by msakai** [comment]
If you are trying to build from Git repository, you need to invoke `git submodule init` and `git submodule update`.

**Comment by yip8** [comment]
I downloaded the zip folder, unpack it which has the name `toysolver-master` and install it by `cabal install`. I ran `git submodule init` and `git submodule update` this time and followed by `cabal install`. Is there any better way of installation?

**Comment by yip8** [comment]
I uninstalled it and install it with git seems to have no problem now. If the installation is correct, is the `toysolver` located in `/dist/build/ToySolver`? If so, I tried:

`./toysolver -help`

and the result is:
`Segmentation fault: 11`. Thanks for your help.

**Comment by msakai** [comment]
Hmm..
Could you give me more information on your environment including your OS, GHC version, etc.?
And are other executable like `toysat` and `toyconvert` also crash in a similar way?

**Comment by msakai** [comment]
If you still have problems, please re-open the issue.
