### ISSUE TITLE
release a toysolver to hackage that builds with 8.8 ... 8.0 please? :)

### ISSUE THREAD

**Issue by cartazio** [msakai/toysolver#25]
would be super handy! 

https://github.com/haskell-CI/haskell-ci has some resources to help generate a full build range, though I / @hvr or others can probably help

**Comment by msakai** [comment]
Sorry for the late response.
I released a new version `0.6.0` to Hackage, and also am currently trying to build with GHC-8.8.

**Comment by cartazio** [comment]
wonderful :)

**Comment by cartazio** [comment]
whats the blockers on 8.8 for you?

**Comment by msakai** [comment]
Sorry for not responding so long.
I released 0.7.0 in February and it is compatible with GHC 8.8 and 8.10.
