### ISSUE TITLE
Installation failed on Debian Linux

### ISSUE THREAD

**Issue by newca12** [msakai/toysolver#6]
OS: Debian Jessy (same problem with Debian Lenny cabal 0.14.0/1.14.0, ghc 7.4.1)
cabal-install version 1.20.0.3 using version 1.20.0.2 of the Cabal library
ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3

Configuring toysolver-0.2.1...
Building toysolver-0.2.1...
Preprocessing library toysolver-0.2.1...

src/ToySolver/Text/PBFile.hs:56:18:
    Could not find module `Data.ByteString.Builder'
    Perhaps you meant
      Data.ByteString.Lazy.Builder (from bytestring-0.10.0.2)
      Data.ByteString.Unsafe (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
Failed to install toysolver-0.2.1
cabal: Error: some packages failed to install:
toysolver-0.2.1 failed during the building phase. The exception was:
ExitFailure 1

The exactly same problem is also describe here :
https://github.com/fpco/streaming-commons/issues/16

FYI : with toysolver version d28e3efc3c41cedb196b44cd6740f79f769ffd70 
Installation is OK with Debian Jessy.

**Comment by msakai** [comment]
Thank you for reporting the problem.
This is because only recent version of bytestring package export Data.ByteString.Builder module, and I didnt't specify proper lower bound of bytestring package.
I believe that the commit 30a69013207c59588d2ba9921dfc6b0e179ac198 has fixed the problem.

**Comment by newca12** [comment]
It works like a charm.
Thanks for the fix.
