### ISSUE TITLE
restriction to base <4.15

### ISSUE THREAD

**Issue by andrewufrank** [msakai/toysolver#78]
The current package (version 0.7.0) has an upper bound on base of <4.15 which precludes compilation with ghc 9 (which uses base 4.15 or higher). It seems that the packages works ok when compiled with "allow newer" relaxation of the upper bounds, which is, however, occasionally interacting with other packages. 

could you check if the bounds can be liftet to <=4.16 to include the current versions of ghc (up to 9.2) and then upload to hackage a maintenance version 0.7.1.

thank you!

**Comment by msakai** [comment]
Sorry, I forgot to reply.

I released version 0.8.0 with `base <4.17` (i.e. GHC <=9.2) to Hackage on 2022-07-26.

Currently, the latest version (0.8.1 revision 1) is with `base <4.19` (i.e. GHC <=9.6).
